// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AiCallRow = { ts: string, provider: string, model: string, purpose: string, input_tokens: bigint, output_tokens: bigint, cost_usd: number, duration_ms: bigint | null, error: string | null, };
