// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "../../../bindings/serde_json/JsonValue";

export type AiOverviewView = { keyword: string, 
/**
 * Raw item; UI extracts text + references. Null when no AI Overview
 * exists for the keyword (DataForSEO returns success + null result).
 */
item: JsonValue, cost_usd: number, estimated_usd: number, };
