// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AiUsageByModel } from "./AiUsageByModel";

export type AiUsageSummary = { days: number, total_calls: bigint, total_cost_usd: number, total_input_tokens: bigint, total_output_tokens: bigint, by_model: Array<AiUsageByModel>, };
