// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AiUsageByModel = { provider: string, model: string, call_count: bigint, input_tokens: bigint, output_tokens: bigint, cost_usd: number, };
