// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AppError = { "kind": "Network", "message": string } | { "kind": "Auth", "message": string } | { "kind": "RateLimit", "message": { family: string, retry_after_secs: number, } } | { "kind": "Validation", "message": string } | { "kind": "Database", "message": string } | { "kind": "Api", "message": { status_code: number, message: string, } } | { "kind": "Parse", "message": string } | { "kind": "Internal", "message": string };
