// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "../../../bindings/serde_json/JsonValue";

export type AuditRun = { id: bigint, target: string, task_id: string | null, max_crawl_pages: number, 
/**
 * 'pending' | 'running' | 'ready' | 'failed'
 */
status: string, started_at: string | null, completed_at: string | null, last_polled_at: string | null, cost_usd: number | null, summary: JsonValue | null, error: string | null, page_count: bigint, };
