// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "../../../bindings/serde_json/JsonValue";

export type AuditPage = { id: bigint, url: string, status_code: number | null, title: string | null, description: string | null, h1: string | null, plain_text_word_count: number | null, page_timing_ttfb: number | null, onpage_score: number | null, raw: JsonValue, };
