// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AutocompleteSuggestion = { suggestion: string | null, relevance: bigint | null, rank_absolute: number | null, };
