// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AutocompleteSuggestion } from "./AutocompleteSuggestion";

export type AutocompleteView = { keyword: string, items: Array<AutocompleteSuggestion>, cost_usd: number, estimated_usd: number, };
