// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "../../../bindings/serde_json/JsonValue";

export type AvailableFiltersView = { result: JsonValue, from_cache: boolean, fetched_at: string | null, };
