// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Filter } from "./Filter";

export type BacklinksIntersectionParams = { targetA: string, targetB: string, 
/**
 * "intersect" (domains linking to both) | "exclude" (linking to A
 * but not B). The frontend toggles between these.
 */
intersectionMode: string, limit: number, offset: number, includeSubdomains: boolean, filter: Filter | null, orderBy: Array<string> | null, };
