// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type BacklinksHistoryParams = { target: string, 
/**
 * YYYY-MM-DD; both ends are optional. DataForSEO defaults to the last
 * available year if not specified.
 */
dateFrom: string | null, dateTo: string | null, };
