// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Filter } from "./Filter";

export type BacklinksPageIntersectionParams = { pages: Array<string>, intersections: number, limit: number, offset: number, includeSubdomains: boolean, filter: Filter | null, orderBy: Array<string> | null, };
