// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Filter } from "./Filter";

/**
 * Inputs for `backlinks_detail`. The frontend builds this; the Rust side
 * validates and clamps. `mode` and `backlinks_status_type` are stringly
 * typed to match DataForSEO; we narrow them here so a typo doesn't reach
 * the API.
 */
export type BacklinksDetailParams = { target: string, 
/**
 * "as_is" | "one_per_domain" | "one_per_anchor"
 */
mode: string, 
/**
 * "all" | "live" | "lost"
 */
status: string, limit: number, offset: number, includeSubdomains: boolean, 
/**
 * Optional filter tree from the visual builder / preset dropdown.
 */
filter: Filter | null, 
/**
 * e.g. ["domain_from_rank,desc"] — passed through verbatim.
 */
orderBy: Array<string> | null, };
