// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Filter } from "./Filter";

/**
 * Inputs for the two list endpoints (referring_domains, anchors). They
 * share the target/limit/offset/filter shape — only the URL differs, which
 * the backend picks based on which command the frontend invokes.
 */
export type BacklinksListParams = { target: string, limit: number, offset: number, includeSubdomains: boolean, filter: Filter | null, orderBy: Array<string> | null, };
