// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "../../../bindings/serde_json/JsonValue";

export type BacklinksDetailView = { target: string, total_count: bigint, items_count: bigint, items: JsonValue, cost_usd: number, estimated_usd: number, };
