// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type BatchSummary = { batch_id: string, total: number, pending: number, ready: number, fetched: number, failed: number, posted_at: string | null, };
