// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type BriefTopResult = { rank: number, url: string, domain: string | null, title: string | null, 
/**
 * Word count from Instant Pages (only fetched for top 3 results).
 */
word_count: number | null, 
/**
 * H2 headings from Instant Pages (top 3 only).
 */
headings: Array<string>, };
