// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type BudgetStatus = { period: string, limit_usd: number | null, alert_at_pct: number | null, spent_usd: number, used_pct: number | null, 
/**
 * "ok" | "alert" | "exceeded" | "no_budget"
 */
state: string, };
