// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type BulkVolumeItem = { keyword: string, search_volume: bigint | null, competition: number | null, competition_level: string | null, cpc: number | null, };
