// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CallLogRow = { ts: string, endpoint: string, mode: string, cost_usd: number, estimated_usd: number | null, request_size: bigint | null, duration_ms: bigint | null, error: string | null, };
