// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TokenUsage } from "./TokenUsage";

export type ChatResponse = { content: string, usage: TokenUsage, model: string, };
