// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ChatSession = { id: bigint, title: string | null, provider: string, model: string, attachment_summary: string | null, created_at: string | null, updated_at: string | null, };
