// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CompetitorDomain } from "./CompetitorDomain";

export type CompetitorsDomainView = { target: string, items: Array<CompetitorDomain>, cost_usd: number, estimated_usd: number, from_cache: boolean, fetched_at: string | null, };
