// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CompetitorDomain = { domain: string | null, avg_position: number | null, sum_position: bigint | null, intersections: bigint | null, };
