// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "../../../bindings/serde_json/JsonValue";

export type DomainRankOverviewView = { target: string, 
/**
 * Raw items array from DataForSEO (one row per metrics shape:
 * organic + paid). UI extracts known fields.
 */
items: JsonValue, cost_usd: number, estimated_usd: number, from_cache: boolean, fetched_at: string | null, };
