// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { IntersectionKeyword } from "./IntersectionKeyword";

export type DomainIntersectionView = { target1: string, target2: string, items: Array<IntersectionKeyword>, cost_usd: number, estimated_usd: number, from_cache: boolean, fetched_at: string | null, };
