// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "../../../bindings/serde_json/JsonValue";
import type { Logical } from "./Logical";
import type { Operator } from "./Operator";

export type Filter = { "kind": "condition", field: string, operator: Operator, value: JsonValue, } | { "kind": "group", 
/**
 * Always 1, 3, 5, ... children.
 */
nodes: Array<Filter>, 
/**
 * Always nodes.len() - 1 connectors.
 */
connectors: Array<Logical>, };
