// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type GapKeyword = { keyword: string, search_volume: bigint | null, keyword_difficulty: number | null, cpc: number | null, rank_yours: number | null, rank_theirs: number | null, 
/**
 * "missing" = competitor ranks, you don't.
 * "weak"    = both rank but competitor outranks you.
 * "strong"  = both rank and you outrank competitor.
 * "unique"  = you rank, competitor doesn't.
 */
bucket: string, };
