// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type IntersectionKeyword = { keyword: string, search_volume: bigint | null, keyword_difficulty: number | null, rank_first: number | null, rank_second: number | null, url_first: string | null, url_second: string | null, };
