// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { KeywordVolume } from "./KeywordVolume";

export type KeywordVolumeBatch = { items: Array<KeywordVolume>, cache_hits: number, fresh: number, cost_usd: number, estimated_usd: number, };
