// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "../../../bindings/serde_json/JsonValue";

export type KeywordVolume = { keyword: string, search_volume: bigint | null, competition: string | null, competition_index: number | null, cpc: number | null, low_top_of_page_bid: number | null, high_top_of_page_bid: number | null, 
/**
 * Trend data (24-month) as raw JSON for the chart.
 */
monthly_searches: JsonValue | null, from_cache: boolean, };
