// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GapKeyword } from "./GapKeyword";

export type KeywordGapView = { yours: string, competitor: string, items: Array<GapKeyword>, missing_count: number, weak_count: number, strong_count: number, unique_count: number, cost_usd: number, estimated_usd: number, };
