// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "../../../bindings/serde_json/JsonValue";

export type KeywordOverviewView = { keyword: string, 
/**
 * Raw item — UI extracts the well-known fields. Shape is large
 * enough that mirroring 30 typed fields would be high churn for
 * little benefit; the page picks the slices it knows.
 */
item: JsonValue, cost_usd: number, estimated_usd: number, from_cache: boolean, fetched_at: string | null, };
