// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "../../../bindings/serde_json/JsonValue";

export type LabsRawView = { 
/**
 * Raw items array — UI extracts the well-known fields per endpoint.
 */
items: JsonValue, cost_usd: number, estimated_usd: number, from_cache: boolean, fetched_at: string | null, };
