// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type LabsKeyword = { keyword: string, search_volume: bigint | null, competition: string | null, competition_index: number | null, cpc: number | null, keyword_difficulty: number | null, };
