// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Mode } from "./Mode";

export type LedgerEntry = { endpoint: string, mode: Mode, cost_usd: number, estimated_usd: number | null, request_size: bigint | null, response_status: bigint | null, duration_ms: bigint | null, task_id: string | null, error: string | null, };
