// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MapsResultItem } from "./MapsResultItem";

export type MapsLiveBatch = { keyword: string, items: Array<MapsResultItem>, cost_usd: number, estimated_usd: number, };
