// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MapsResultItem = { kind: string, rank_absolute: number | null, title: string | null, url: string | null, domain: string | null, address: string | null, phone: string | null, rating: number | null, rating_count: bigint | null, place_id: string | null, category: string | null, };
