// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "../../../bindings/serde_json/JsonValue";

export type OnPageInstantView = { url: string, 
/**
 * Items array from the Instant Pages response. The first row holds
 * the audit; the UI extracts known sections (meta, content, checks).
 */
items: JsonValue, cost_usd: number, estimated_usd: number, from_cache: boolean, fetched_at: string | null, };
