// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "../../../bindings/serde_json/JsonValue";

export type OnPageItemsView = { items: JsonValue, items_count: bigint, total_count: bigint, cost_usd: number, estimated_usd: number, from_cache: boolean, fetched_at: string | null, };
