// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Operator = "eq" | "ne" | "gt" | "lt" | "ge" | "le" | "in" | "not_in" | "like" | "not_like" | "ilike" | "not_ilike" | "match" | "not_match";
