// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Project = { id: bigint, name: string, target: string, created_at: string | null, };
