// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RankedKeyword = { keyword: string, search_volume: bigint | null, competition: string | null, cpc: number | null, keyword_difficulty: number | null, rank_absolute: number | null, serp_url: string | null, etv: number | null, };
