// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RankPoint = { fetched_at: string, rank_absolute: number | null, url: string | null, };
