// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "../../../bindings/serde_json/JsonValue";

export type SearchIntentView = { 
/**
 * Raw items array — each item has `keyword` + `keyword_intent.label`
 * (informational/commercial/navigational/transactional) +
 * `secondary_keyword_intents` array.
 */
items: JsonValue, cost_usd: number, estimated_usd: number, from_cache: boolean, fetched_at: string | null, };
