// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SerpTask = { task_id: string, batch_id: string, keyword: string, location_code: number, language_code: string, depth: number, status: string, posted_at: string | null, fetched_at: string | null, poll_attempts: number, cost_usd: number | null, error: string | null, };
