// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SerpCompetitor = { domain: string | null, avg_position: number | null, median_position: number | null, rating: number | null, etv: number | null, count: bigint | null, };
