// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SerpResultItem } from "./SerpResultItem";

export type SerpLiveBatch = { keyword: string, items: Array<SerpResultItem>, cost_usd: number, estimated_usd: number, };
