// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type StoredChatMessage = { id: bigint, session_id: bigint, role: string, content: string, prompt_template_id: string | null, input_tokens: number | null, output_tokens: number | null, cost_usd: number | null, created_at: string | null, };
