// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type StoredSerpItem = { task_id: string, position: number, kind: string, url: string | null, title: string | null, description: string | null, domain: string | null, };
