// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SerpTask } from "./SerpTask";
import type { StoredSerpItem } from "./StoredSerpItem";

export type TaskBatchStatus = { batch_id: string, tasks: Array<SerpTask>, results: { [key in string]?: Array<StoredSerpItem> }, };
