// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TaskBatchId = { batch_id: string, task_count: number, cost_usd: number, estimated_usd: number, };
