// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "../../../bindings/serde_json/JsonValue";

export type TechnologiesView = { domain: string, 
/**
 * Whole result blob — has `domain`, `last_visited_date`,
 * `country_iso_code`, `language_code`, `content_language_code`,
 * `meta`, and a `technologies` map. UI extracts `technologies`.
 */
result: JsonValue, cost_usd: number, estimated_usd: number, from_cache: boolean, fetched_at: string | null, };
