// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BriefRelatedKeyword } from "./BriefRelatedKeyword";
import type { BriefTopResult } from "./BriefTopResult";

export type TopicBriefView = { seed: string, 
/**
 * Median word count across the top 3 results that were audited.
 */
recommended_word_count: number | null, min_word_count: number | null, max_word_count: number | null, 
/**
 * H2/H3 headings that appeared in 2+ of the audited top results
 * — signals what topics the SERP expects you to cover.
 */
common_headings: Array<string>, 
/**
 * Up to 20 related keywords with volume + KD.
 */
related_keywords: Array<BriefRelatedKeyword>, 
/**
 * Top 10 SERP results, with metrics for the top 3.
 */
top_results: Array<BriefTopResult>, 
/**
 * Sum of search volume across the related keyword set.
 */
total_volume_potential: bigint, 
/**
 * Average KD across the related keyword set (NaN-safe; 0 if empty).
 */
avg_difficulty: number, cost_usd: number, estimated_usd: number, from_cache: boolean, fetched_at: string | null, };
