// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TrackedKeyword } from "./TrackedKeyword";

export type TrackedKeywordWithRank = { keyword: TrackedKeyword, 
/**
 * Latest recorded rank (NULL = unranked or never checked).
 */
current_rank: number | null, 
/**
 * Rank from the previous run, for the ▲/▼ change indicator.
 */
previous_rank: number | null, 
/**
 * Most recent SERP url where the target appeared, if any.
 */
current_url: string | null, };
