// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TrackedKeyword = { id: bigint, target: string, keyword: string, location_code: number, language_code: string, frequency: string, active: boolean, created_at: string | null, last_run_at: string | null, };
