// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "../../../bindings/serde_json/JsonValue";

export type TrendsView = { keywords: Array<string>, 
/**
 * Raw items array — UI charts the `google_trends_graph` item and
 * renders `google_trends_topics_list` / `google_trends_queries_list`
 * if present.
 */
items: JsonValue, cost_usd: number, estimated_usd: number, from_cache: boolean, fetched_at: string | null, };
