// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UsageByEndpoint } from "./UsageByEndpoint";

export type UsageSummary = { days: number, total_calls: bigint, total_cost_usd: number, total_estimated_usd: number, by_endpoint: Array<UsageByEndpoint>, };
