// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UsageByEndpoint = { endpoint: string, call_count: bigint, cost_usd: number, };
