// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "../../../bindings/serde_json/JsonValue";

export type WhoisView = { domain: string, 
/**
 * Raw item from DataForSEO. Many fields; the page picks the ones it
 * recognises (registrar, dates, name servers, status).
 */
item: JsonValue, cost_usd: number, estimated_usd: number, from_cache: boolean, fetched_at: string | null, };
